library(shiny)
# TERMINEI A LESSON 3
# Define UI for application that draws a histogram
shinyUI(fluidPage(
    
    # Application title
    titlePanel(h3("PRODUÇÃO CREDIÁRIO")),
    
    # Sidebar with a slider input for the number of bins
    sidebarLayout(
        sidebarPanel(
            #imageOutput("logo"),
#            img(src="./CetelemAtual.png", height = 100, width = 100),
#            fluidRow(
#                column(width = 10,
#                selectInput("selectTpDash", label = h5("Tipo do Dashboard"), 
#                                 choices = list("Produção Contratos" = 1, "Taxas Médias" = 2, "Percentual em Produção" = 3), 
#                                 selected = 1),
#                     
#                     hr())
#            ),
            #fluidRow(width = 10,  
          # criar em server um vetor com estes textos e passar como parametro o indice. 
          # no server pega o texto e usa
            fluidRow(   
              selectInput("selectChn", label = h5("Tipo de Crediário"),
                             choices = list(
                               "TOTAL CETELEM"= 1,
                               "02 PAGAMENTO DIGITAL2" = 2,
                               "03 PAGAMENTO DIGITAL" = 3,
                               "2G PNEUS" = 4,
                               "4 AM" = 5,
                               "A CONSTRUJAN" = 6,
                               "A M PNEUS" = 7,
                               "ACABAMENTOS BEL LAR LTDA" = 8,
                               "ACHAQUI MAT DE CONST MATRIZ" = 9,
                               "ACIMEL" = 10,
                               "AGENCIAS DIRETO" = 11,
                               "AGROBOI" = 12,
                               "AH MODAS" = 13,
                               "AMERICANAS.COM" = 14,
                               "AMIGAO SUPERMERCADO" = 15,
                               "ANABRU FASHION" = 16,
                               "AQUI AGORA CONFECOES" = 17,
                               "ARAPU" = 18,
                               "ARARA FERRAGENS" = 19,
                               "ARMARINHOS FERNANDO" = 20,
                               "ATACADAO CENTRO SUL" = 21,
                               "ATACADO MUNHOZ" = 22,
                               "AUTO CENTER DANIEL" = 23,
                               "AUTO PECAS MINHA DEUZA" = 24,
                               "AUTO PECAS PADRE CICERO" = 25,
                               "BABY CENTER" = 26,
                               "BALAROTI" = 27,
                               "BANCO BGN" = 28,
                               "BANCO DE AREIA CPO GRANDE" = 29,
                               "BARCELONA MATS CONTRUCAO" = 30,
                               "BAZAR MULTIMIL LINS" = 31,
                               "BEIJA FLOR DE NILOPOLIS" = 32,
                               "BEIRA RIO MAT P CONST" = 33,
                               "BELLI OTICA" = 34,
                               "BELMIROS" = 35,
                               "BERGAMAIS" = 36,
                               "BERGAMINI" = 37,
                               "BESNI" = 38,
                               "BEST SHOP TV INTERNET" = 39,
                               "BIGOLIN" = 40,
                               "BIGOLIN ERECHIM" = 41,
                               "BIGOLIN MAT CONSTRUCAO" = 42,
                               "BIGOLIN PARANA" = 43,
                               "BOM PRECO BOQUEIRAO" = 44,
                               "BONS VIZINHOS" = 45,
                               "BORDIGNON QUATIGUA" = 46,
                               "BRANNER" = 47,
                               "BRASIMAR III" = 48,
                               "CAÇULA DE PNEUS" = 49,
                               "CAMPO GRANDE MATERIAIS DE CONS" = 50,
                               "CARAJAS MAT CONSTRUCAO LTDA" = 51,
                               "CARTAO CETELEM AURA" = 52,
                               "CASA DA SOGRA MATRIZ" = 53,
                               "CASA DAS LINHAS" = 54,
                               "CASA DE TINTAS" = 55,
                               "CASA DOS PISOS" = 56,
                               "CASA E VIDEO MATRIZ" = 57,
                               "CASA MEI" = 58,
                               "CASA NOVA MOVEIS" = 59,
                               "CASA SHOW" = 60,
                               "CASAS FRANKLIN" = 61,
                               "CASAS JARDIM MATRIZ" = 62,
                               "CASTOR CENTER" = 63,
                               "CAVALIN SUPERMERCADO" = 64,
                               "CECOMIL" = 65,
                               "CEGIL SUPER MERCADO DE MAT CON" = 66,
                               "CELDOM BARRA DA TIJUCA" = 67,
                               "CELIA MODAS" = 68,
                               "CELULAR MIX IBIRAPUERA MATRIZ" = 69,
                               "CENTER BOX SUPERMERCADOS II" = 70,
                               "CENTER CASTILHO SBC MATRIZ" = 71,
                               "CENTRAL SURF" = 72,
                               "CENTRO ELETRICO" = 73,
                               "CERAMICAS NAC REUNIDAS" = 74,
                               "CERQUEIRA GONCALVES" = 75,
                              "CHALANA SUPERMERCADOS" = 76,
                              "CHARM CALCADOS SUZANO I" = 77,
                              "CHOCOLANDIA" = 78,
                              "CIMFEL" = 79,
                              "CINCAL PNEUS" = 80,
                              "COBERARTE MATS CONSTRUCAO" = 81,
                              "CODIGO GIRLS GUARULHOS" = 82,
                              "COLOMBO" = 83,
                              "COLORADO CONSTRUCAO" = 84,
                              "COMERCIAL 2001" = 85,
                              "COMERCIAL FERNANDES" = 86,
                              "COMERCIAL LOPES" = 87,
                              "COMERCIAL PAMPULHA" = 88,
                              "COMERCIAL RAMOS MATRIZ" = 89,
                              "COMJOL" = 90,
                              "COMPRAFACIL INTERNET" = 91,
                              "COMPRE MAIS" = 92,
                              "COMPUTER STORE" = 93,
                              "CONCRET MAT CONSTRUCAO" = 94,
                              "CONDOR SUPER CENTER MATRIZ" = 95,
                              "CONSTAT" = 96,
                              "CONSTRUCAO E CIA" = 97,
                              "CONSTRUCENTER" = 98,
                              "CONSTRUREDE" = 99,
                              "CONTRULAR" = 100,
                              "COPEL COLCHOES" = 101,
                              "CORDEIRO PECAS E SERV AUTO" = 102,
                              "CRUZEIRO DO SUL" = 103,
                               "CURINGA DOS PNEUS" = 104,
                              "DALLA BERNARDINA" = 105,
                              "DECATHLON" = 106,
                              "DELL COMPUTADORES" = 107,
                              "DELTA PNEUS" = 108,
                              "DELUC" = 109,
                              "DEMILAR" = 110,
                              "DEPOSITO ALENCAR" = 111,
                              "DEPOSITO LITORAL PARANAGUA" = 112,
                              "DICASA" = 113,
                              "DIPOLLINI CALCADOS" = 114,
                              "DISTRIBUIDORA CAMPEAO" = 115,
                              "DISTRIBUIDORA CRISTIANO MAT DE" = 116,
                              "DOC DOG" = 117,
                              "DORINHOS" = 118,
                              "DROGALIS" = 119,
                               "DROGARIA LUZITHANIA" = 120,
                               "ELETRO E CIA" = 121,
                               "ELETROCITY" = 122,
                               "ELETRORARO COMERCIO DE ELETROD" = 123,
                              "ELMO" = 124,
                              "ERVATI MOVEIS" = 125,
                              "ESPACO TIL" = 126,
                              "ESPANTALHO PNEUS" = 127,
                              "ESPLANADA MOVEIS" = 128,
                              "ESTRELA SUPERMERCADO ITAQUA" = 129,
                              "ETNA HOME STORE" = 130,
                              "EXTRABOM" = 131,
                               "F ALMEIDA E CIA LTDA" = 132,
                              "FAN PRESENTES" = 133,
                              "FARMACIA PERMANENTE MATRIZ" = 134,
                              "FARMACIAS NOSSA TRATICOL" = 135,
                              "FAST SHOP" = 136,
                              "FAVORITA" = 137,
                              "FAVORITO" = 138,
                              "FERRAGENS PARAIBA" = 139,
                              "FLAMBOYANT" = 140,
                              "FLEXPE MOGI MATRIZ LJ 101" = 141,
                              "FLU LOOK" = 142,
                              "FNAC" = 143,
                              "FOTO OTICA NACOES" = 144,
                               "FOTOPTICA" = 145,
                              "GABRIELLA CALCADOS" = 146,
                              "GIASSI SUPERMERCADOS" = 147,
                              "GILSON PNEUS" = 148,
                              "GIMENES SUPERMERCADO" = 149,
                              "GOIANAO MAT P CONSTRUCAO" = 150,
                              "GRUPO 01 HERMOL" = 151,
                              "GRUPO BENERI" = 152,
                              "GRUPO RAMSONS" = 153,
                              "GUARANA BRASIL" = 154,
                              "H3BRASIL PRESIDENTE PRUDENTE" = 155,
                               "HITECH COMPUTADORES VITORIA I" = 156,
                               "HM PLANEJADOS" = 157,
                              "HOT POINT" = 158,
                               "IMAGINE" = 159,
                              "INCOSPEL" = 160,
                               "INFORMATICA NACIONAL SA" = 161,
                              "IRMAOS SOARES" = 162,
                               "IT CENTER MATRIZ" = 163,
                              "ITA SUPERMERCADOS" = 164,
                               "ITAMAQUINAS" = 165,
                              "J MONTE CENTER CONSTRUCOES" = 166,
                               "JACARE MADEIRAS E COMPENSADOS" = 167,
                              "JET E JOTAL" = 168,
                               "JL MEURER" = 169,
                              "JLN MAT DE CONST" = 170,
                               "JOCICAL MATS CONSTRUCAO" = 171,
                               "JOLI" = 172,
                               "JORLAN VEICULOS" = 173,
                              "JURANDIR PIRES" = 174,
                              "JV TUBOS E ACABAMENTOS" = 175,
                              "KALUNGA" = 176,
                               "KANGURU" = 177,
                              "KATEL CELULAR" = 178,
                               "KICASA MATRIZ" = 179,
                              "KOLUMBUS MOVEIS" = 180,
                               "LE BISCUIT" = 181,
                              "LE POSTICHE" = 182,
                               "LE POSTICHE LICENCIADAS" = 183,
                              "LIVRARIA CONCORDE" = 184,
                               "LOGIN INFORMATICA" = 185,
                              "LOJAS BAZZAR" = 186,
                               "LOJAS BECKER" = 187,
                              "LOJAS CUNHA" = 188,
                               "LOJAS DUJUCA TOMBOS" = 189,
                              "LOJAS IMPERADOR" = 190,
                               "LOJAS MAGAL" = 191,
                              "LOJAS NIPON MATRIZ" = 192,
                               "LOJAS RITZ FLUMINENSE" = 193,
                              "M K" = 194,
                               "MADEREIRA PRIMA" = 195,
                              "MADUREIRA SHOPPING" = 196,
                               "MAGAZINE RENATO" = 197,
                              "Mais - Cacique" = 198,
                               "Mais - Casa Sol Família" = 199,
                              "Mais - Casa Sol Lins" = 200,
                               "Mais - Casa Sol Madeiras" = 201,
                              "Mais - Casa Sol Marília" = 202,
                               "Mais - Casa Sol Max" = 203,
                              "Mais - Construmarques" = 204,
                               "Mais - Lopez e Gimenez" = 205,
                              "Mais - Moretto" = 206,
                               "MAIS VALDIR" = 207,
                              "MALUI MALHAS JD AGARI" = 208,
                               "MARABRAZ" = 209,
                              "MARGARITA SAO GONCALO" = 210,
                               "MARKO INFORMATICA" = 211,
                              "MASSAFRA" = 212,
                               "MAXI TENNIS" = 213,
                              "MAXIMO SUPERMERCADO" = 214,
                               "MAXIMUNDIAL" = 215,
                              "MEGA CENTER CASA E CONSTRUCAO" = 216,
                               "MEGA SHOW" = 217,
                              "MERCADAO DAS MALHAS" = 218,
                               "MERCADINHO CARONE" = 219,
                              "MERCADO PABITTI" = 220,
                               "MERCADO PAGO" = 221,
                              "MICROCENTER" = 222,
                               "MIHARA FCO MORATO" = 223,
                              "MINI PREÇO" = 224,
                               "MISTAO" = 225,
                              "MM INFORMATICA" = 226,
                               "MN CENTER MATRIZ" = 227,
                              "MOBILIADORA UNIVERSAL" = 228,
                               "MOLLICA SANTA CECILIA" = 229,
                              "MOMAR RETIRO" = 230,
                               "MONAX" = 231,
                              "MOVEIS PAGANINI" = 232,
                               "MOVEISLAR" = 233,
                              "MUITO MAIS LAR" = 234,
                               "MUITO MAIS LAR SANTA CATARINA" = 235,
                              "MULTICASA" = 236,
                               "MULTICEL" = 237,
                              "MUTIRAO MATERIAL DE CONSTRUCAO" = 238,
                               "NAKASHIMA" = 239,
                              "NELISE CALCADOS" = 240,
                               "NICOM MATS CONSTRUCAO" = 241,
                              "NIVALMIX" = 242,
                               "NORDESTAO" = 243,
                              "O CENTRO ELETRICO LTDA" = 244,
                               "O FAZENDAO COM MAT CONSTRUCAO" = 245,
                              "O VERGALHAO" = 246,
                               "OBRADEC MAT DE CONSTRUCAO LTDA" = 247,
                              "OTICA DA GENTE" = 248,
                               "OTICA GIL LANCASTER" = 249,
                              "OTICAS CAROL" = 250,
                               "OTICAS IX" = 251,
                              "OVERBACK JACAREPAGUA" = 252,
                               "PACHECO PNEUS" = 253,
                              "PADOVANI MATS CONSTRUCAO" = 254,
                               "PAGAMENTO DIGITAL" = 255,
                              "PALOMAX" = 256,
                               "PANAMERICANO CONSIGNADO" = 257,
                              "PAPEL E CIA" = 258,
                               "PARACARD" = 259,
                              "PARAGOMINAS" = 260,
                               "PASSAPORTE GRANE RIO" = 261,
                              "PB KIDS" = 262,
                               "PEDROSO SUPERMERCADO" = 263,
                              "PELICANO" = 264,
                               "PHARMACIA ALQUIMIA 2" = 265,
                              "PILOTO MASTERCARD CHIP" = 266,
                              "PISOLAR" = 267,
                              "PLANET GIRLS" = 268,
                              "PLUG USE" = 269,
                              "PNEUS 56" = 270,
                              "PNEUSOLA" = 271,
                              "POLAR TINTAS" = 272,
                              "PONTAL CALCADOS" = 273,
                              "PORTUGAL DESCARTAVEIS" = 274,
                              "POSTO SETE ESTRELAS MTZ" = 275,
                              "POTIGUAR" = 276,
                              "PRIME TEK COMPUTADORES" = 277,
                              "PRIME TEK COMPUTADORES" = 278,
                              "PRINCESS FLORENCE" = 279,
                              "PROLAR DUQUE DE CAXIAS" = 280,
                               "PROPLASTIK" = 281,
                              "QUEIROZ E FILHOS" = 282,
                               "QUIVER SURF SHOP" = 283,
                              "RAMAGE MODAS" = 284,
                               "REDE AMIGOS SUPERMERCADOS" = 285,
                              "REDE CEM PORCENTO COLI" = 286,
                               "REDE CONSTRUIR" = 287,
                              "REDE CONSTRUIR" = 288,
                               "REDE DA CONSTRUCAO" = 289,
                              "REDE MAIS - CONFIANÇA SUPERMERCADOS" = 290,
                               "REDE MAIS - DATERRA SUPERMERCADO" = 291,
                              "REDE MAIS - GAMA SUPERMERCADO" = 292,
                               "REDE MAIS - J ARAUJO" = 293,
                              "REDE MAIS - JL MEDEIROS" = 294,
                               "REDE MAIS - MAIS VENEZA" = 295,
                              "REDE MAIS - MARIO & FILHO COML" = 296,
                               "REDE MAIS - MJ DE GOIS" = 297,
                              "REDE MAIS - OPCAO SUPERMERCADOS" = 298,
                               "REDE MAIS - REDE MAIS GA GOIS" = 299,
                              "REDE MAIS - SERVE BEM" = 300,
                               "REDE MAIS - TEIXEIRA DA SILVA" = 301,
                              "REDE MAIS - VENANCIO SUPERMERCADOS" = 302,
                               "REDE MAIS - VENEZA SUPERMERCADO" = 303,
                              "RELOJOARIA SUISSA" = 304,
                               "RESGATE" = 305,
                              "RH CETELEM" = 306,
                               "RN INFORMATICA" = 307,
                              "RODA MODA" = 308,
                               "RODAR PNEUS" = 309,
                              "ROGE MOVEIS E ELETRODOMESTICOS" = 310,
                               "ROMAO CALCADOS" = 311,
                              "SALES MAT CONSTR" = 312,
                               "SALIM PNEUS" = 313,
                              "SAMOM MATERIAL DE CONSTRUCAO" = 314,
                               "SANUZA" = 315,
                              "SEM CADEIA" = 316,
                               "SENIOR" = 317,
                              "SHOP DOS COLCH ES" = 318,
                               "SHOPP TELHAS" = 319,
                              "SHOPPING INT. GUARULHOS" = 320,
                               "SHOPPING METRO TATUAPE" = 321,
                              "SHOPPING VIDA S O JO O" = 322,
                               "SHOPTIME" = 323,
                              "SO REPAROS ASA NORTE" = 324,
                               "SOFERRO" = 325,
                              "SPEED CAR GAS" = 326,
                               "SPINOLA MATERIAS DE CONSTRU  O" = 327,
                              "SPORT MASTER" = 328,
                               "STAR COMPUTER" = 329,
                              "STARPOINT" = 330,
                               "STRUTURA" = 331,
                              "SUBMARINO" = 332,
                               "SUPER MASTER" = 333,
                              "SUPER MUFFATO" = 334,
                               "SUPERMERCADO ALABARCE" = 335,
                              "SUPERMERCADO AMAZONIA" = 336,
                               "SUPERMERCADO CARIOCA" = 337,
                              "SUPERMERCADO CARNEIRO" = 338,
                               "SUPERMERCADO COMETA" = 339,
                              "SUPERMERCADO ECONOMIA" = 340,
                               "SUPERMERCADO GALASSI" = 341,
                              "SUPERMERCADO IBIUNA" = 342,
                               "SUPERMERCADO LOJAM" = 343,
                              "SUPERMERCADO PEDREIRA" = 344,
                               "SUPERMERCADO PEREIRA" = 345,
                              "SUPERMERCADO RR" = 346,
                               "SUPERMERCADO STA CATARINA MTZ" = 347,
                              "TABIRA FILMES" = 348,
                               "TAKARA" = 349,
                              "TATENO MIRANDOPOLIS MATRIZ" = 350,
                               "TBD" = 351,
                              "TECIPLAST DE NOVA IGUACU" = 352,
                               "TECNOPLUS" = 353,
                              "TELHANORTE" = 354,
                               "TEND TUDO" = 355,
                              "TIAO ROCHA 3" = 356,
                               "TIARA BOLSAS" = 357,
                              "TID S BAZAR NOVA IGUA U" = 358,
                               "TNG SAO PAULO" = 359,
                              "TOK STOK" = 360,
                               "TONIN SUPERMERCADO" = 361,
                              "TRIFERRO" = 362,
                               "TUMELERO" = 363,
                              "TUMKUS E TUNCKUS" = 364,
                               "TUPAN" = 365,
                              "TUPAN CONSTRUCOES" = 366,
                               "UBA MOVEIS" = 367,
                              "UNIT DE ICARAI COM DE ART" = 368,
                               "UNITINTAS LTDA" = 369,
                              "VERONA" = 370,
                               "VIANENSE" = 371,
                              "VILELA SUPERMERCADO" = 372,
                               "VSA INFORMATICA" = 373,
                              "WORLD TIRES" = 374,
                               "WR ITABORAI" = 375
                               ), 
                             selected = 1),                
                hr()
               
                #fluidRow(column(6, verbatimTextOutput("value")))                
            ),
            fluidRow(   
              radioButtons("radioTpCred", label = h5("Canal de Origem"),
                           choices = list("Normal" = 1, "Simplificado" = 2), 
                           selected = 1),                
              hr()
              
              #fluidRow(column(6, verbatimTextOutput("value")))                
            ),
            #fluidRow(width = 10,
            fluidRow(
                    radioButtons("radioEntr", label = h5("Entrada"),
                             choices = list("Com" = 1, "Sem" = 2), 
                             selected = 2),                
                hr()
                
                #fluidRow(column(3, verbatimTextOutput("value")))                
            ),
            #fluidRow(width = 10,
            fluidRow(
                radioButtons("radioSys", label = h5("Pagamento no Fluxo"),
                             choices = list("Sim" = 1, "Não" = 2), 
                             selected = 2),                
                hr()
                
                #fluidRow(column(3, verbatimTextOutput("value")))                
            ),
            helpText('Para os gráficos, a linha azul mostra a tendência dos dados,
                        enquanto a região em cinza mostra o intervalo de confiança
                        (valores fora dessa região tem probabilidade baixa de ocorrência,
                        5%, devendo ser investigados)')
        ),        
        # Show a plot of the generated distribution
        mainPanel(
            tabsetPanel(
                #tabPanel('Tabela Geral',
                #     #    dataTableOutput("mytable1")),
                #div(dataTableOutput("mytable1"), style = "font-size:70%")),
                tabPanel('Contratos',
                         plotOutput("distPlot1", height = "800px", width = "1100px")),
                tabPanel('Taxa Média',
                         plotOutput("distPlot2", height = "800px", width = "1100px")),
                tabPanel('% de Montante',
                         plotOutput("distPlot3", height = "800px", width = "1100px"))
            )
        )
    )
))